-- Leif's private working area on an Application, and the one index that
-- stopped him keeping a to-do beside it.
--
-- Two things, and they belong together because they are the same need:
-- while reviewing an application he wants to write down what he is
-- thinking, and write down what he must do before deciding.
--
-- WHY A THIRD NOTES TABLE AND NOT contact_notes.
-- A Contact may have several Applications. Reasoning about one of them
-- must not surface on another, and a Contact-scoped note cannot express
-- that: there is no honest way to ask "which application was I talking
-- about". So application_notes joins contact_notes and deal_notes as a
-- sibling, with the same shape and the same semantics. It is not a second
-- notes system — the same components render it, through the existing
-- `reference` prop they already carry.
--
-- WHY THE TASK INDEX CHANGES.
-- tasks_one_open_review_per_application was named for one invariant and
-- enforced a broader one: keyed on application_id alone, it allowed only
-- ONE open task of ANY type per Application. Since an overdue Application
-- normally HAS an open review_application task, adding a follow-up task
-- was refused outright:
--
--   duplicate key value violates unique constraint
--   "tasks_one_open_review_per_application"
--
-- The predicate now says what the name always said. Nothing relied on the
-- broader reading: schedule_application_review_escalations() guards with
-- its own `not exists (... and t.type = 'review_application' ...)`, and
-- review_application() closes the review task by type too, so neither
-- function's behaviour changes. (That function's inline comment still
-- describes the old index. It is left exactly as it is: 02_functions.sql
-- must stay byte-identical to pg_dump, and rewriting a function to edit a
-- comment buys a phantom diff for nothing.)
--
-- Deterministic: creates structure and nothing else. No business row is
-- read, written or asserted, so it replays into an empty database and
-- stays out of the replay manifest.

-- ---------------------------------------------------------------------
-- 1. Leif's notes on one Application
-- ---------------------------------------------------------------------
create table if not exists public.application_notes (
  id bigint generated by default as identity primary key,
  -- Exactly one Application. Cascades with it, like contact_notes does
  -- with its Contact: a note about a record that no longer exists is not
  -- history worth keeping, it is an orphan.
  application_id bigint not null,
  text text,
  date timestamp with time zone default now(),
  -- Who wrote it. Same nullable shape as the sibling tables, so a note
  -- survives a sales record being removed.
  sales_id bigint,
  attachments jsonb[]
);

alter table public.application_notes
  drop constraint if exists application_notes_application_id_fkey;
alter table public.application_notes
  add constraint application_notes_application_id_fkey
  foreign key (application_id) references public.applications(id)
  on update cascade on delete cascade;

alter table public.application_notes
  drop constraint if exists application_notes_sales_id_fkey;
alter table public.application_notes
  add constraint application_notes_sales_id_fkey
  foreign key (sales_id) references public.sales(id)
  on update cascade on delete set null;

-- The only way this table is ever read: one Application's notes, newest
-- first.
create index if not exists application_notes_application_id_idx
  on public.application_notes (application_id, date desc);

-- ---------------------------------------------------------------------
-- 2. Reachable by Leif, by nobody else
-- ---------------------------------------------------------------------
-- These are his private working notes about a person's application. The
-- applicant must never be able to read them, so `anon` gets nothing —
-- the same posture as deal_notes, and the same revoke that the security
-- posture work made deterministic.
alter table public.application_notes enable row level security;

drop policy if exists "Enable read access for authenticated users" on public.application_notes;
create policy "Enable read access for authenticated users"
  on public.application_notes for select to authenticated using (true);

drop policy if exists "Enable insert for authenticated users only" on public.application_notes;
create policy "Enable insert for authenticated users only"
  on public.application_notes for insert to authenticated with check (true);

drop policy if exists "Application Notes Update Policy" on public.application_notes;
create policy "Application Notes Update Policy"
  on public.application_notes for update to authenticated using (true);

drop policy if exists "Application Notes Delete Policy" on public.application_notes;
create policy "Application Notes Delete Policy"
  on public.application_notes for delete to authenticated using (true);

grant all on table public.application_notes to anon;
grant all on table public.application_notes to authenticated;
grant all on table public.application_notes to service_role;
revoke select, insert, update, delete on table public.application_notes from anon;

-- ---------------------------------------------------------------------
-- 3. One open REVIEW task per Application — which is what it always meant
-- ---------------------------------------------------------------------
drop index if exists public.tasks_one_open_review_per_application;
create unique index tasks_one_open_review_per_application
  on public.tasks (application_id)
  where done_date is null
    and application_id is not null
    and type = 'review_application';

-- ---------------------------------------------------------------------
-- 4. Self-proving
-- ---------------------------------------------------------------------
-- Asserts the SHAPE, never a count of rows written, so it replays into an
-- empty database unchanged. The task rules are proved by exercising them
-- against throwaway rows inside a savepoint that is always rolled back.
do $$
declare
  v_contact bigint;
  v_offer bigint;
  v_app_a bigint;
  v_app_b bigint;
  v_second_review_refused boolean := false;
begin
  -- The notes table exists, is row-level secured, and anon cannot touch it.
  if not exists (
    select 1 from pg_tables
     where schemaname = 'public' and tablename = 'application_notes'
       and rowsecurity
  ) then
    raise exception 'application_notes must exist with row level security';
  end if;

  if exists (
    select 1
      from information_schema.role_table_grants
     where table_schema = 'public'
       and table_name = 'application_notes'
       and grantee = 'anon'
       and privilege_type in ('SELECT', 'INSERT', 'UPDATE', 'DELETE')
  ) then
    raise exception 'anon must not reach Leifs private application notes';
  end if;

  -- A note must belong to an Application. Nothing else is a note here.
  if exists (
    select 1 from information_schema.columns
     where table_schema = 'public' and table_name = 'application_notes'
       and column_name = 'application_id' and is_nullable = 'YES'
  ) then
    raise exception 'application_notes.application_id must be NOT NULL';
  end if;

  -- The other context invariants are untouched.
  if (select count(*) from pg_indexes
       where schemaname = 'public'
         and indexname in ('tasks_one_open_per_onboarding_item',
                           'tasks_one_open_per_offboarding_item',
                           'tasks_one_open_per_cadence_issue',
                           'tasks_one_open_per_sales_call_type',
                           'tasks_one_open_review_per_application')) <> 5 then
    raise exception 'a task context invariant went missing';
  end if;

  -- And the narrowed one really does say "review".
  if not exists (
    select 1 from pg_indexes
     where schemaname = 'public'
       and indexname = 'tasks_one_open_review_per_application'
       and indexdef like '%review_application%'
  ) then
    raise exception 'the review-task index is not scoped to review_application';
  end if;

  -- Now prove the BEHAVIOUR, on rows that cannot survive.
  --
  -- Everything below runs inside a subtransaction that is always rolled
  -- back: the block ends by raising a sentinel, and the handler swallows
  -- only that one. So the fixtures never persist, and a real failure
  -- still propagates and fails the migration.
  --
  -- This is deliberately not "insert, check, delete". Deleting would have
  -- to succeed in a database where contact deletion is closed on purpose
  -- and an Application's answers refuse even a cascading delete — a
  -- cleanup that cannot run is how a migration leaves fixtures in
  -- production.
  select id into v_offer from public.offers order by id limit 1;
  if v_offer is null then
    -- An empty database has no Offer to hang an Application on. The shape
    -- assertions above are the whole proof there; the behavioural ones
    -- run wherever there is something to attach to.
    return;
  end if;

  begin
    insert into public.contacts
      (first_name, last_name, email_jsonb, phone_jsonb, tags,
       sales_eligibility, first_seen, last_seen)
    values ('Index', 'Assertion', '[]'::jsonb, '[]'::jsonb, '{}',
            'normal', now(), now())
    returning id into v_contact;

    -- raw_answers '{}' on purpose: materialize_native_application_responses()
    -- skips an empty payload, so these fixtures never create the immutable
    -- response rows that would refuse to be rolled away.
    insert into public.applications
      (contact_id, source, status, submitted_at, raw_answers, offer_id)
    values (v_contact, 'manual', 'pending', now(), '{}'::jsonb, v_offer)
    returning id into v_app_a;

    insert into public.applications
      (contact_id, source, status, submitted_at, raw_answers, offer_id)
    values (v_contact, 'manual', 'pending', now(), '{}'::jsonb, v_offer)
    returning id into v_app_b;

    -- One open review task per Application, still enforced.
    insert into public.tasks (contact_id, application_id, type, text, status, due_date)
    values (v_contact, v_app_a, 'review_application', 'review', 'pending', now());

    begin
      insert into public.tasks (contact_id, application_id, type, text, status, due_date)
      values (v_contact, v_app_a, 'review_application', 'second', 'pending', now());
    exception when unique_violation then
      v_second_review_refused := true;
    end;

    if not v_second_review_refused then
      raise exception 'a second open review_application task must be refused';
    end if;

    -- A review task plus several manual follow-ups: allowed, which is the
    -- whole point of this migration.
    insert into public.tasks (contact_id, application_id, type, text, status, due_date)
    values (v_contact, v_app_a, 'other', 'email about schedule', 'pending', now()),
           (v_contact, v_app_a, 'other', 'review again Friday', 'pending', now()),
           (v_contact, v_app_a, 'follow_up', 'clarify support needs', 'pending', now());

    if (select count(*) from public.tasks
         where application_id = v_app_a and done_date is null) <> 4 then
      raise exception 'one review task and three follow-ups should coexist';
    end if;

    -- A different Application is independent, review task and all.
    insert into public.tasks (contact_id, application_id, type, text, status, due_date)
    values (v_contact, v_app_b, 'review_application', 'review b', 'pending', now());

    if (select count(*) from public.tasks
         where application_id = v_app_b and done_date is null) <> 1 then
      raise exception 'applications must not share task uniqueness';
    end if;

    -- Notes are isolated by Application, for the same Contact.
    insert into public.application_notes (application_id, text)
    values (v_app_a, 'thinking about A'), (v_app_a, 'more about A'),
           (v_app_b, 'thinking about B');

    if (select count(*) from public.application_notes where application_id = v_app_a) <> 2
       or (select count(*) from public.application_notes where application_id = v_app_b) <> 1 then
      raise exception 'application notes must not leak between applications';
    end if;

    -- Deciding an Application closes its REVIEW task and leaves Leif's own
    -- to-dos alone.
    update public.tasks
       set done_date = now(), status = 'completed'
     where application_id = v_app_a and type = 'review_application';

    if (select count(*) from public.tasks
         where application_id = v_app_a and done_date is null) <> 3 then
      raise exception 'closing the review task must not close the follow-ups';
    end if;

    raise exception 'ASSERTIONS_PASSED_ROLL_BACK_THE_FIXTURES';
  exception
    when others then
      if sqlerrm <> 'ASSERTIONS_PASSED_ROLL_BACK_THE_FIXTURES' then
        raise;
      end if;
  end;
end $$;
